version: '3'

services:
    reverse-proxy:
        # Traefik v2.2 officiel
        image: traefik:v2.2
        ports:
            # Ports d'écoute
            - "80:80"
            # Dashboard
            - "8080:8080"
        volumes:
            # Mapping de la configuration statique
            - ./traefik.yml:/etc/traefik/traefik.yml
            # Mapping du dossier de conf dynamique
            - ./dyn_traefik/:/etc/dyn_traefik/
            # Pour que traefik puisse écouter les events Docker
            - /var/run/docker.sock:/var/run/docker.sock
    front:
        image: fullstack/frontend:0.1
        build: ./front
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.http.routers.front.rule=Host(`multitransports.com`)

    back:
        image: fullstack/backend:0.1
        build: .
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.http.routers.backend.rule=Host(`backend.multitransports.com`)

